from __future__ import annotations

from collections.abc import Callable
from typing import Protocol


class BrowserDriver(Protocol):
    @property
    def is_connected(self) -> bool: ...

    @property
    def needs_browser_restart(self) -> bool: ...

    async def connect(self) -> None: ...
    async def new_tab(self) -> str: ...
    async def wait_for_composer(self) -> None: ...
    async def ensure_chat_surface(self) -> None: ...
    async def select_effort_model(self, model: str, /) -> None: ...
    async def set_effort_power_position(self, position: int, /) -> dict[str, object]: ...
    async def dismiss_transient_controls(self) -> None: ...
    async def dom_state(self) -> dict[str, object]: ...
    async def eval(self, expression: str, /) -> object: ...
    async def clear_composer(self) -> None: ...
    async def arm_page_send_probe(self) -> None: ...
    def arm_send_capture(self) -> dict[str, object]: ...
    async def type_message(self, message: str, /) -> None: ...
    async def click_send(self) -> None: ...
    async def page_send_probe(self) -> dict[str, object]: ...
    def captured_send_response(
        self, capture: dict[str, object], /
    ) -> tuple[str, int] | None: ...
    def clear_send_capture(self, capture: dict[str, object], /) -> None: ...
    async def clear_page_send_probe(self) -> object: ...
    async def close_context(self, context: str, /) -> None: ...
    async def close(self) -> None: ...


DriverFactory = Callable[[], BrowserDriver]
